import {Command} from "../../command";
import {MessageEmbed} from "discord.js";

const gifs = ["https://c.tenor.com/kK8D7hQXX5wAAAAC/coins-tails.gif", "https://c.tenor.com/nEu74vu_sT4AAAAC/heads-coinflip.gif"]

const cmd = new Command('randomteams', 'Generate random teams with the users in the same voice channel of the sender', i => {
    const teamsCount = i.options.getNumber("teams");

    if (i.member.voice.channel && i.member.voice.channel.members.size >= teamsCount) {
        const members = i.member.voice.channel.members;
        const teams = [];
        for (let i = 0; i < teamsCount; i++) {
            const possibleMembers = members.filter(m => !teams.flat().includes(m));
            for (let j = 0; j < Math.floor(members.size / teamsCount); j++) {
                const member = possibleMembers.random();
                if (!teams[i]) teams[i] = [];
                teams[i].push(member);
            }
        }
        const embed = new MessageEmbed();
        embed.setTitle("Random teams");
        embed.setColor("RANDOM");
        embed.setFooter({text: "Generated by " + i.user.tag.split("#")[0], iconURL: i.user.displayAvatarURL()});
        embed.setTimestamp();
        teams.forEach((t, i) => {
            embed.addField("Team " + (i + 1), t.map(m => m.user.tag.split("#")[0]).join("\n"));
        });
        i.reply({embeds: [embed]});
    } else i.reply({
        content: "You must be in a voice channel with enough people to use this command !",
        ephemeral: true
    });
});

cmd.data.addNumberOption(i => i.setName('teams').setDescription('The number of teams to generate').setRequired(true).setMaxValue(10).setMinValue(2));

export default cmd;

